# Generated by Django 3.0.3 on 2020-05-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_image', models.ImageField(null=True, upload_to='art_img')),
                ('label', models.CharField(blank=True, max_length=25)),
            ],
        ),
    ]
