# Generated by Django 3.0.3 on 2020-06-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cassandra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
