# Generated by Django 3.0.3 on 2020-06-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cassandra', '0002_art_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
