# Generated by Django 3.0.3 on 2020-06-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cassandra', '0004_auto_20200609_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ImageField(null=True, upload_to='journal_img')),
                ('label', models.CharField(blank=True, max_length=25)),
                ('year', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
